complete -c valo -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_use_subcommand" -f -a "screen" -d 'A simple command that changes screen backlight level.'
complete -c valo -n "__fish_use_subcommand" -f -a "keyboard" -d 'A simple command that changes MacBooks\' keyboard backlight level.'
complete -c valo -n "__fish_use_subcommand" -f -a "completions" -d 'Generate tab-completion scripts for your shell'
complete -c valo -n "__fish_use_subcommand" -f -a "version" -d 'Show version'
complete -c valo -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c valo -n "__fish_seen_subcommand_from screen" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from screen" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from screen" -f -a "get" -d 'Get current keyboard backlight brightness value'
complete -c valo -n "__fish_seen_subcommand_from screen" -f -a "get-percentage" -d 'Get current keyboard backlight brightness percentage value'
complete -c valo -n "__fish_seen_subcommand_from screen" -f -a "set" -d 'Set backlight brightness as value'
complete -c valo -n "__fish_seen_subcommand_from screen" -f -a "set-percentage" -d 'Set backlight brightness as percentage value'
complete -c valo -n "__fish_seen_subcommand_from screen" -f -a "up" -d 'Increase backlight brightness by percentage value'
complete -c valo -n "__fish_seen_subcommand_from screen" -f -a "down" -d 'Decrease backlight brightness by percentage value'
complete -c valo -n "__fish_seen_subcommand_from screen" -f -a "max" -d 'Set backlight brightness as max'
complete -c valo -n "__fish_seen_subcommand_from screen" -f -a "off" -d 'Turn off backlight'
complete -c valo -n "__fish_seen_subcommand_from screen" -f -a "breathing-light" -d 'Perform breathing light mode'
complete -c valo -n "__fish_seen_subcommand_from screen" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c valo -n "__fish_seen_subcommand_from get" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from get" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from get-percentage" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from get-percentage" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from set" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from set" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from set-percentage" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from set-percentage" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from up" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from up" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from down" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from down" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from max" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from max" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from off" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from off" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from breathing-light" -l step
complete -c valo -n "__fish_seen_subcommand_from breathing-light" -l delay
complete -c valo -n "__fish_seen_subcommand_from breathing-light" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from breathing-light" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from keyboard" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from keyboard" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from keyboard" -f -a "get" -d 'Get current keyboard backlight brightness value'
complete -c valo -n "__fish_seen_subcommand_from keyboard" -f -a "get-percentage" -d 'Get current keyboard backlight brightness percentage value'
complete -c valo -n "__fish_seen_subcommand_from keyboard" -f -a "set" -d 'Set backlight brightness as value'
complete -c valo -n "__fish_seen_subcommand_from keyboard" -f -a "set-percentage" -d 'Set backlight brightness as percentage value'
complete -c valo -n "__fish_seen_subcommand_from keyboard" -f -a "up" -d 'Increase backlight brightness by percentage value'
complete -c valo -n "__fish_seen_subcommand_from keyboard" -f -a "down" -d 'Decrease backlight brightness by percentage value'
complete -c valo -n "__fish_seen_subcommand_from keyboard" -f -a "max" -d 'Set backlight brightness as max'
complete -c valo -n "__fish_seen_subcommand_from keyboard" -f -a "off" -d 'Turn off backlight'
complete -c valo -n "__fish_seen_subcommand_from keyboard" -f -a "breathing-light" -d 'Perform breathing light mode'
complete -c valo -n "__fish_seen_subcommand_from keyboard" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c valo -n "__fish_seen_subcommand_from get" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from get" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from get-percentage" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from get-percentage" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from set" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from set" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from set-percentage" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from set-percentage" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from up" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from up" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from down" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from down" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from max" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from max" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from off" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from off" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from breathing-light" -l step
complete -c valo -n "__fish_seen_subcommand_from breathing-light" -l delay
complete -c valo -n "__fish_seen_subcommand_from breathing-light" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from breathing-light" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from completions" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from completions" -f -a "bash" -d 'Generate shell completion for Bash'
complete -c valo -n "__fish_seen_subcommand_from completions" -f -a "zsh" -d 'Generate shell completion for Zsh'
complete -c valo -n "__fish_seen_subcommand_from completions" -f -a "fish" -d 'Generate shell completion for Fish'
complete -c valo -n "__fish_seen_subcommand_from completions" -f -a "powershell" -d 'Generate shell completion for PowerShell'
complete -c valo -n "__fish_seen_subcommand_from completions" -f -a "elvish" -d 'Generate shell completion for Elvish'
complete -c valo -n "__fish_seen_subcommand_from completions" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c valo -n "__fish_seen_subcommand_from bash" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from bash" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from zsh" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from zsh" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from fish" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from fish" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from powershell" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from powershell" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from elvish" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from elvish" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from version" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from version" -s V -l version -d 'Prints version information'
complete -c valo -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c valo -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
